title: Lego's Stuff
lang: en-AU
description: >- # this means to ignore newlines until "baseurl:"
  Tools, guides, and other goodies
baseurl: ""
url: "https://legofigure11.github.io"
twitter_username: LegoFigure11
github_username:  legofigure11

# host: 0.0.0.0

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
