title: Lego's Stuff
lang: en-AU
description: >- # this means to ignore newlines until "baseurl:"
  Tools and other stuff
baseurl: ""
url: "https://legofigure11.github.io"
twitter_username: LegoFigure11
github_username:  legofigure11

host: 0.0.0.0

github:
  repository_url: https://github.com/LegoFigure11/legofigure11.github.io/
  owner_name: LegoFigure11
  owner_url: https://github.com/LegoFigure11/

plugins:
  - jekyll-seo-tag
